### ISSUE TITLE
AxisArray images?

### ISSUE THREAD

**Issue by timholy** [jw3126/UnitfulRecipes.jl#32]
I'd like to implement a recipe for images stored as an AxisArray with unitful axes. Should I add it here, or are you trying to keep this package as lightweight as possible?

**Comment by briochemc** [comment]
I think UnitfulRecipes.jl remaining lightweight is a nice feature. Maybe @jw3126's [AxisArrayPlots](https://github.com/jw3126/AxisArrayPlots.jl) is a good package to update for this? Or a new one?

Anyway @jw3126 and you are very likely more capable than me to know what's best 😅

**Comment by timholy** [comment]
I don't disagree. I was unaware of AxisArrayPlots. I see that's not a registered package, so I'll wait for @jw3126 to chime in.

**Comment by jw3126** [comment]
Yeah, I would prefer not to depend on `AxisArrays` with `UnitfulPlots`. Especially since `AxisArrays` does not look super maintained? 
I did not use [AxisArrayPlots](https://github.com/jw3126/AxisArrayPlots.jl) for a long time. It does not contain much code, but is somewhat opinionated. So I think rolling a new package, might be the best option.
