### ISSUE TITLE
Vector{Any} doesn't plot

### ISSUE THREAD

**Issue by DanDeepPhase** [jw3126/UnitfulRecipes.jl#52]
Vector{Any} errors out when stripping units

```julia
using Unitful, Plots, UnitfulRecipes  
x=(1:10)u"m"
y=[]  
for n in x  
    push!(y,n^2)  
end  
plot(x,y)

```

`
ERROR: DimensionError: Inf and 1.0 m^2 are not dimensionally compatible.
`

I tried initialize the empty vector as `Vector{Quantity}()` but that didn't help. I don't know how to initialize it to include the types for the fields.

**Comment by briochemc** [comment]
Yes, this package can only dispatch on the recipes if the type contains the unit. You could do either
```julia
y = x.^2 # or y = [v^2 for v in x]
```
for `y` to have the correct type or — if you really need to preallocate `y` — then you must get the element-type right from the start, for example with
```julia
y_eltype = typeof(x[1]^2) # Quantity{Int64, 𝐋², Unitful.FreeUnits{(m²,), 𝐋², nothing}}
y = y_eltype[] # now has the correct eltype to start with
for n in x
    push!(y,n^2)
end
```

**Comment by briochemc** [comment]
Does this solve your problem? (If yes, feel free to close this issue! 😃)

**Comment by DanDeepPhase** [comment]
This workaround solves my problem, and i can now make vectors that plot. 

I didn't understand that it was the type of the vector and not the type of the scalar that was driving the recipe.

Thanks for the help

**Comment by briochemc** [comment]
> I didn't understand that it was the type of the vector and not the type of the scalar that was driving the recipe.

Yes that's exactly it. As a general Julia rule, it's always good to [avoid arrays with abstract types](https://docs.julialang.org/en/v1/manual/performance-tips/#man-performance-abstract-container), like `Any`. So best to avoid starting with `x = []` because it creates an empty vector of type `Any`. If you know the size `S` and type `T`, an efficient way to preallocate is to do something like:
```julia
julia> T = Float32
Float32

julia> S = (2,3)
(2, 3)

julia> x = Array{T}(undef, S)
2×3 Matrix{Float32}:
 6.35031f-27  3.17791f-26  0.0
 1.0f-45      1.0f-45      0.0
```

or if you are not chasing every last bit of performance, I like to fill it with a default value:

```julia
julia> x = fill(NaN32, S)
2×3 Matrix{Float32}:
 NaN  NaN  NaN
 NaN  NaN  NaN
```
